### ISSUE TITLE
SSL protocol issues requires TLSv1

### ISSUE THREAD

**Issue by db260179** [nerzhul/ownCloud-SMS-App#151]
### Steps to reproduce
1.Turn off TLSv1 on nginx settings
2.Watch nginx error log - set to debug
3. Error 13 occurs, turn TLSv1 back on, connection works again.

### Expected behaviour
TLSv1.1 and 1.2 is considered to be safe, should not be forced to use TLSv1 or older protocols?

### Actual behaviour
SSL handshake refuses to connect

### Server configuration

**NextCloud/ownCloud version:**
8.2

**PHP version:**
5.7

**HTTPd server:**
nginx 1.6.2

**Database engine & version:** 
mysql 5.6

### Client configuration

**Android version:**
4.4

**Phone:**

**NextCloud SMS app version:**
latest

### Logs

```
 [info] 31963#31963: *11 SSL_do_handshake() failed (SSL: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol) while SSL handshaking, client: x.x.x.xx.x, server: x.x.x.x.x:443
```

This error is a bit of a red herring as showing SSLv3, but same issue for TLSv1

**Comment by db260179** [comment]
Android 4.4.4 supports TLSv1.1 and 1.2, this is the only app that needs tls 1.0, the other apps work fine with tlsv1.0 turned off on the nginx instance.

**Comment by nerzhul** [comment]
it's android choice as we use Android http client to perform all those actions, cannot fix it

**Comment by db260179** [comment]
As your code is using httpclient, is there no way to force select the TLS protocols?

**Comment by nerzhul** [comment]
@db260179 i can look at this but i'm very busy on other projects atm

**Comment by db260179** [comment]
Hi Loic,

No worries, this issue was bugging me just wanted to highlight the issue to
you guys.

Thanks

**Comment by nerzhul** [comment]
Okay i find what is the problem it's in our ssl context create we are specifying SSL, i add TLSv1.2 fallback 1.1 fallback 1.0 fallback SSL

**Comment by nerzhul** [comment]
fixed by ceba0324e1ae92ac4edd2104cb4736d7f8706902

**Comment by moutonjr** [comment]
@nerzhul : Still getting the very same problem on 1.2.4 (commercial version), trying to access my Nextcloud server.

My server is behind a reverse proxy that exposes wildcard certificate signed by my own CA (which has been downloaded in Android userland cert store). 

The scheme is foundable as follows : `openssl s_client -host jfile.jserv.fr -port 443`

Can you repoen this issue for tag 1.4.2 ?

**Comment by nerzhul** [comment]
hi @moutonjr it's not the same issue, here it was a SSL selection problem, yours is a trusted anchor issue, can you open another issue for it, please ?

**Comment by moutonjr** [comment]
@nerzhul : my bad, it's more like a feature request for handling untrusted certificates or CAs. I fixed it by adding an X509 version with "basicConstraints: CA:TRUE" on the CA itself.
