### ISSUE TITLE
couldn't establish http connection, make sure http server is there

### ISSUE THREAD

**Issue by mlyszczek** [nerzhul/ownCloud-SMS-App#163]
### Steps to reproduce
1. Add account and log in into nextcloud server

### Expected behaviour
Logging in should succed

### Actual behaviour
logging in ends with error "couldn't establish http connection, make sure http server is there". This error occurs both for HTTP and HTTPS

### Server configuration

**Nextcloud version:**
12.0.3

**PHP version:**
7.0.25

**Webserver:**
nginx 1.12.1

**HTTPS:**
self-signed certificate

### Client configuration

**Android version:**
7.1 (paranoid android 7.3.1)

**Phone:**
Nexus 5x

**Nextcloud SMS app version:**
1.3.0 (from f-droid)

### Logs

```
11-12 05:52:38.942 12420 12420 I fr.unix_experience.owncloud_sms.activities.LoginActivity.UserLoginTask: _serverURL = http://next-cloud.server
11-12 05:52:38.945 12420 12592 I fr.unix_experience.owncloud_sms.engine.OCHttpClient: Perform GET http://next-cloud.server/index.php/apps/ocsms/get/apiversion?format=json

11-12 05:53:09.789 12420 12592 W fr.unix_experience.owncloud_sms.activities.LoginActivity.UserLoginTask: Failed to login, OCSyncException occured: null
```

Logs from nginx access while logging in

```
10.1.1.82 - lm- [12/Nov/2017:05:52:12 +0100] "POST /index.php/apps/ocsms/get/apiversion?format=json HTTP/1.1" 405 5 "-" "nextcloud-phonesync (1.3.0)"
```

There is no GET operation in nginx access log. For comparision, version 1.2.5 that works sends

```
10.1.1.82 - lm- [12/Nov/2017:05:58:12 +0100] "GET /index.php/apps/ocsms/get/apiversion?format=json HTTP/1.1" 200 13 "-" "nextcloud-phonesync (1.2.5)"
```

### Workaround
Install version 1.2.5 <- works well, exports smses

**Comment by sercasbh** [comment]
Also here.
Same issue

**Comment by DJaeger** [comment]
I have the same issue.
The workaround is working for me

**Comment by Pascaloub** [comment]
Same issue here

nextcloud SMS 1.3.1 installed from Google Play repository
android 6.0
apache 2.4
SSL cert with commercial CA install (tested and work without any warning on any web browser)

**Comment by runout-at** [comment]
same here

**Comment by nerzhul** [comment]
Hello,
thanks for your report.
This issue was solved in 1.3.2 released yesterday, the new HTTP native Android client has one bug in a specific code path which has been fixed

**Comment by sercasbh** [comment]
When will be 1.3.2 on f-droid?
Thank you for your work.
Bye

**Comment by Pascaloub** [comment]
update 1.3.2 from google play done.

Problem remain exactly the same.

**Comment by nerzhul** [comment]
Please don't ask me for f-droid i don't manage it

**Comment by hackitz** [comment]
i have tried a few different versions of owncloud-sms and still get the error 
"couldn't establish http connection, make sure http server is there". 
The error occurs both for HTTP and HTTPS
i have the latest stable version on nextcloud and am running android 8.0 on my phone.

**Comment by nerzhul** [comment]
i published 1.3.4 which fix an anoying timeout problem regression when talking to server on periodic synchronization. Tell me if it's okay for you

**Comment by hackitz** [comment]
i have the latest version of nextcloud sms. i still get the error
unable to perform a http connection, please ensure there is a web server.

**Comment by hackitz** [comment]
just tried with http not https and the http gives the same error.

**Comment by hackitz** [comment]
where are the logs located?

**Comment by nerzhul** [comment]
@hackitz use "adb logcat" with android platform tools installed
